#pragma once

#include <boost/preprocessor/stringize.hpp>

#define APPLICATION_MAJOR_VERSION 0
#define APPLICATION_MINOR_VERSION 3
#define APPLICATION_REVISION 3
#define APPLICATION_VERSION BOOST_PP_STRINGIZE(APPLICATION_MAJOR_VERSION) "." BOOST_PP_STRINGIZE(APPLICATION_MINOR_VERSION) "." BOOST_PP_STRINGIZE(APPLICATION_REVISION)
#define APPLICATION_DESCRIPTION "Pierry"
#define APPLICATION_COPYRIGHT "Copyright(C) Fuji Xerox Advanced Technology Co., Ltd. 2014 All rights reserved."
